# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
  -  stage: 
     jobs:
       - job: 
pool:
        name: Azure Pipelines
        demands:
        - SpecialSoftware # Check if SpecialSoftware capability exists

